### ISSUE TITLE
Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by timsayshey** [savolai/JPEG-Autorotate#1]
First, thanks for such a great tool! Just running into an issue.

I keep getting this error randomly. I tested this in version 1 and 2.

Here's a screenshot of the error output:
![silverelite](https://cloud.githubusercontent.com/assets/1148940/21359214/1dfa4c5a-c6a1-11e6-97cb-851973053e08.png)

Maybe just add a try catch to prevent the error from ending the operation?

Thanks!

**Comment by savolai** [comment]
Thanks for your message!

Sorry though, but I don't maintain jhead, which is at the heart of basically all of JPEG Autorotate's actual rotating functionality. Also, to me, jhead source seems like C code, no exceptions there.

You might want to contact jhead author, http://www.sentex.net/~mwandel/jhead/

**Comment by savolai** [comment]
There is a bounty of 25 euro available for fixing this. Please contact me, Olli to receive the bounty if you have a fix. Successfully rotating the files attached to this comment with a patched version of JPEG Autorotate you send is the criteria for receiving the bounty. 

"I hereby give you permission to use all files (attachments) I sent to you in my email from Wed 16/05/2018 15:06 GMT in relation to fixing or developing the app JPEG_Autorotate. I remain copyright holder of the images. I will also commit to paying you, or another developer, who fixes the app, a one-time payable fee of 25 euro. 

I also volunteer myself for testing new app releases in relation to auto rotating images.

Once the bug is fixed, I do would like to get a copy of the software for my own use. 😊

If you need anything else, let me know. "
![files for testing sent wed 16-05-2018 1506 gmt-1](https://user-images.githubusercontent.com/844183/43099398-be8d20a0-8eca-11e8-9af2-84b9d478118a.jpg)
![20180516_144926](https://user-images.githubusercontent.com/844183/43099403-c53418f0-8eca-11e8-95c8-836f3caae4ca.jpg)
![20180516_145001](https://user-images.githubusercontent.com/844183/43099404-c555adda-8eca-11e8-91eb-9ff201826407.jpg)
![20180516_145308](https://user-images.githubusercontent.com/844183/43099406-c5753eac-8eca-11e8-93dd-0f1f94b97362.jpg)
![20180516_145312](https://user-images.githubusercontent.com/844183/43099407-c5965a7e-8eca-11e8-8f9f-9acad19abec6.jpg)
![overview test photos](https://user-images.githubusercontent.com/844183/43099408-c5b59b0a-8eca-11e8-9832-4e3f29a1a734.jpg)
![screenshot autorotate error](https://user-images.githubusercontent.com/844183/43099409-c5d5f0e4-8eca-11e8-86b3-76f61f42357b.png)

**Comment by savolai** [comment]
A partial solution to make rotating continue after the error is to not delegate globbing to jhead but to do it in powershell

ls -r -ea silentlycontinue -fo -inc "*.jpg" | % { $_.fullname } | %{z:\JPEG-Autoro
tate\jhead.exe -autorot $_}

of course, since the error is actually non-fatal, it would be much better to actually get jpegtran to do the actual rotation anyway.

Not sure if using exiftran instead of jhead+jpegtran would work better.

**Comment by James-Jaw** [comment]
"Invalid SOS parameters for sequential JPEG" solution, by james jaw,  Taiwan ,ROC 
step:
1. rename jpegtran.exe to jpegtran2018.exe
2. creat a batch file ,filename=jpegtran.bat
3. batch file content as follow
jpegtran2018  %1 %2 %3 %4 %5 %6 
if errorlevel 1 copy %5 %6 /y 
4.run jhead.exe for auto rotate someone.jpg as follow
jhead -autorot  someone.jpg

**Comment by savolai** [comment]
Wow! Sorta hacky, but impressive. Mind sending a patch? Thanks. 🙂

**Comment by savolai** [comment]
my apologies for not remembering to report here - in the case of the above user above: his issue apparently got solved  another way already so I'm not sure he's willing to pay the bounty anymore, but I'll be happy to incorporate the fix to 2.0 if you can verify this is tested to work. 

Olli

**Comment by savolai** [comment]
Hi @James-Jaw!

Wow! Sorta hacky, but impressive. Mind sending a patch? Thanks. 🙂

I already replied but now that I look at your solution more, I'm not sure I quite understand it. Could you explain the last steps?
Does this rotate photos even when the SOS parameters are not right? I guess not, since that an issue with jhead. 

Also this solution I think has the same downside as my above powershell solution - it does not rotate the erroneous photos. The photos CAN actually be rotated, just not with jhead. So I think the correct solution is one where the photos with bad metadata actually get rotated.

Also, my apologies for not remembering to report here - in the case of the above user above: his issue apparently got solved  another way already so I'm not sure he's willing to pay the bounty anymore. I can ask, or you can do so directly, just email me at olli at jpegrotate dot com.

Still, I'll be happy to add your fix to 2.0 if you can send me a merge request/patch that you have tested to work. 

Olli

**Comment by James-Jaw** [comment]
Hi,Olli

I know that errors can still be rotated when using jpegtran (but the DPI of exif data will be changed)

However, if you want to automatically correct the jhead batch, jhead will be interrupted due to jpegtran error.

I just let jhead call jpegtran rotation, it can be completed smoothly, not to be interrupted by jpengtran.

Use jhead in addition to automatic rotation, you can also summarize photos in different photo date folders,like follow batch file
jhead -n%%Y-%%m%%d\\%%f -autorot *.jpg

Or you can have a better and simpler way to auto-rotate and summarize photos in different photo-taking folders.

Thank you

Wishful

James  2019-0826

**Comment by savolai** [comment]
Thanks! 
I'm marking this closed as this is fixed in JPEG Autorotate 3 that is about to be released. I you would still like to send a merge request for the exact changes that might help for version 2, that's still welcome.
Take care,
Olli

**Comment by James-Jaw** [comment]
hi

**Comment by James-Jaw** [comment]
HI,
I updated my original batch file to install JPEG_AutoRotate for your reference. This installation also solves the bug that you generated in JPEG_autorotate_2-1b.exe due to "SOS" error.
There should be 5 files in the folder as follows:
1.	jhead.exe
2.	jpegtran2018.exe (rename from jpegtran.exe)
3.	jpegtran.bat
@echo off
jpegtran2018  %1 %2 %3 %4 %5 %6  > nul 
if errorlevel 1 copy %5 %6 /y > nul
4.	install.bat
@echo off
:install
rem copy execute file
    copy /y jhead.exe         %SystemRoot%\system32
    copy /y jpegtran2018.exe  %SystemRoot%\system32
    copy /y jpegtran.bat      %SystemRoot%\system32
rem registe
    reg ADD HKCR\Directory\shell\Lossless.Rotate /ve /d JpgAutoRotate↑	
reg add HKCR\Directory\shell\Lossless.Rotate\command /ve /d "cmd.exe /c cd \\"%%1\\" && copy /y %SystemRoot%\system32\jpegtran\*.\* && jhead -autorot \*.jpg && del /q jpegtran\*.\*"
5.	unstall.bat
@echo off
:uninstall
rem del execute file
    del /q %SystemRoot%\system32\jhead.exe
    del /q %SystemRoot%\system32\jpegtran.bat
    del /q %SystemRoot%\system32\jpegtran2018.exe
rem registe
    reg delete HKCR\Directory\shell\Lossless.Rotate /f
    reg delete HKCR\Directory\shell\Lossless.Rotate\command /f

My English is not good, the forum is not very useful, So I don't know how to pass the file to you.
just hope to share!  Thanks!

Take care, 2
James 2019-0826

**Comment by savolai** [comment]
Thanks James!
